[package]
name = "egg-rpc"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
egg-types = { path = "../egg-types" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
