[package]
name = "egg-node"
version = "0.1.0"
edition = "2021"

[dependencies]
egg-net = { path = "../egg-net" }
egg-chain = { path = "../egg-chain" }
egg-db = { path = "../egg-db" }
egg-types = { path = "../egg-types" }
egg-crypto = { path = "../egg-crypto" }
